GET http://localhost:3000/commentaire/2

###
POST http://localhost:3000/commentaire
Content-Type: application/json

{
  "email": "achrafhammi29@gmail.com",
  "contenu": "bon travail",
  "articleId": 1
}

###
POST http://localhost:3000/commentaire
Content-Type: application/json

{
  "email": "hardizi@gmail.com",
  "contenu": "bon travail2",
  "articleId": 1
}

###

PATCH http://localhost:3000/commentaire/1
Content-Type: application/json

{
  "contenu": "testing"
}
###

DELETE http://localhost:3000/commentaire/2

