DELETE http://localhost:3000/users/2
Content-Type: application/json


###
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
  "password": "test"
}

###
GET http://localhost:3000/users/1
Accept: application/json

###
POST http://localhost:3000/users/
Content-Type: application/json

{
  "nom": "HAMMIAchraf",
  "email": "achrafhammi29@gmail.com",
  "password": "testing123",
  "role": "ADMIN"
}

###

POST http://localhost:3000/users/
Content-Type: application/json

{
  "nom": "HARDIZIAchraf",
  "email": "achrafhardizi29@gmail.com",
  "password": "testing1223",
  "role": "ADMIN"
}

###


